Updated to 5th version of the Pascal-P compiler -- pascal-p5

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,75 +1,214 @@
 #!/bin/bash
+################################################################################
 #
-# Set up compiler to use.
+# Configure scipt for Pascal-P5
 #
-# Presently implements:
+# Sets up the complete Pascal-P5 project.
 #
-# IP Pascal, named "ip_pascal"
-#
-# GPC Pascal, named "GPC" (or "gpc")
-#
+################################################################################
 
-if [ -z "$1" ]
-then
+#
+# Check command exists
+#
+# Uses the bash "command" built in.
+#
+function checkexists {
 
-   echo "*** Error: Missing parameter"
-   echo "*** Must be \"ip_pascal\" or \"gpc\""
-   exit 1
+    command -v $1 >/dev/null
+    rc=$?
+    if [[ $rc != 0 ]] ; then
+
+        echo "*** No $1 was found"
+
+    fi
+
+}
+
+#
+# Set default variables
+#
+compiler="gpc"
+bits="32"
+host="linux"
+
+#
+# Determine if needed programs exist. The only fatal one is grep, because we
+# need that to run this script. The rest will impact the running of various
+# test and build scripts.
+#
+checkexists grep
+if [[ $rc != 0 ]] ; then
+
+    exit 1
 
 fi
 
-if [ $1 = "ip_pascal" ]
+checkexists diff
+checkexists sed
+checkexists rm
+checkexists cp
+checkexists mv
+
+checkexists flip > /dev/null
+
+if [[ $rc != 0 ]] ; then
+
+    echo -n "flip does not exist"
+    echo $PATH | grep -q "$PWD/bin" || echo -n ", has PATH been set up?"
+    echo
+    echo "attempting to make it"
+    gcc -o ./bin/flip ./c_support/flip.c
+    checkexists flip > /dev/null
+    flip=$rc
+    if [[ $rc != 0 ]] ; then
+
+        echo "*** Unable to make flip"
+
+    fi
+
+fi
+checkexists ls
+checkexists zip
+
+#
+# Check user arguments
+#
+for var in "$@"
+do
+
+    if [ $var = "--help" ]
+    then
+
+        echo "Configure program for Pascal-P5"
+        echo
+        echo "--gpc:       Select GPC as target compiler"
+        echo "--p5c:       Select p5c as target compiler"
+        echo "--ip_pascal: Select IP Pascal as target compiler"
+        echo "--32:        Select 32 bit target"
+        echo "--64:        Select 64 bit target"
+        echo
+        exit 0
+
+    elif [ $var = "--gpc" ]
+    then
+
+        compiler="gpc"
+
+    elif [ $var = "--p5c" ]
+    then
+
+        compiler="p5c"
+
+    elif [ $var = "--ip_pascal" ]
+    then
+
+        compiler="ip_pascal"
+
+    elif [ $var = "--32" ]
+    then
+
+        bits="32"
+
+    elif [ $var = "--64" ]
+    then
+
+        bits="64"
+
+    fi
+
+done
+
+
+if [ $compiler = "p5c" ]; then
+    checkexists "$P5CDIR/$compiler" > /dev/null
+    if [[ $rc != 0 ]] ; then
+        echo "p5c not found - has environment variable P5CDIR been set?"
+        compiler=""
+        # fatal this for now
+        exit 1
+    fi
+else
+    checkexists $compiler
+    if [[ $rc != 0 ]] ; then
+        compiler=""
+        # fatal this for now
+        exit 1
+    fi
+fi
+
+
+if [ $compiler = "gpc" ]
+then    gpc -v 2> temp
+    grep "gpc version 20070904" temp > /dev/null
+    rc=$?
+    if [[ $rc != 0 ]] ; then
+
+        echo "*** Warning, Pascal-P5 is only validated to work with gpc version 20070904"
+
+    fi
+    grep "build=x86_64" temp > /dev/null
+    rc=$?
+    if [[ $rc == 0 ]] ; then
+
+        bits="64"
+
+    fi
+
+fi
+
+if [ $compiler = "ip_pascal" ] || [ $compiler = "IP_Pascal" ]
 then
 
    #
    # Set up for IP Pascal
    #
-   cp ip_pascal/p5.bat      p5.bat
-   cp ip_pascal/compile.bat compile.bat
-   cp ip_pascal/run.bat     run.bat
-   cp ip_pascal/cpcom.bat   cpcom.bat
-   cp ip_pascal/cpint.bat   cpint.bat
+   echo "Set up for IP Pascal"
+   cp ip_pascal/p5.bat      bin/p5.bat
+   cp ip_pascal/compile.bat bin/compile.bat
+   cp ip_pascal/run.bat     bin/run.bat
 
-   cp ip_pascal/p5          p5
-   cp ip_pascal/compile     compile
-   cp ip_pascal/run         run
-   cp ip_pascal/cpcom       cpcom
-   cp ip_pascal/cpint       cpint
+   cp ip_pascal/p5          bin/p5
+   cp ip_pascal/compile     bin/compile
+   cp ip_pascal/run         bin/run
+
+   cp ip_pascal/Makefile    .
 
    cp ip_pascal/standard_tests/iso7185pat.cmp standard_tests
    cp ip_pascal/standard_tests/iso7185pats.cmp standard_tests
 
-   echo Compiler set to IP Pascal
+   #
+   # IP Pascal does not care about line endings, but returning to DOS mode
+   # line endings normalizes the files for SVN checkin.
+   #
+   #unixeol
 
-elif [ $1 = "gpc" ] || [ $1 = "GPC" ]
-then 
+elif [ $compiler = "gpc" ] || [ $compiler = "p5c" ]
+then
 
    #
-   # Set up for GPC Pascal
+   # Set up for chosen Pascal compiler
    #
-   cp gpc/p5.bat      p5.bat
-   cp gpc/compile.bat compile.bat
-   cp gpc/run.bat     run.bat
-   cp gpc/cpcom.bat   cpcom.bat
-   cp gpc/cpint.bat   cpint.bat
+   echo "Set up for $compiler"
+   cp $compiler/p5.bat      bin/p5.bat
+   cp $compiler/compile.bat bin/compile.bat
+   cp $compiler/run.bat     bin/run.bat
 
-   cp gpc/p5          p5
-   cp gpc/compile     compile
-   cp gpc/run         run
-   cp gpc/cpcom       cpcom
-   cp gpc/cpint       cpint
 
-   cp gpc/standard_tests/iso7185pat.cmp standard_tests
-   cp gpc/standard_tests/iso7185pats.cmp standard_tests
+   cp $compiler/p5          bin/p5
+   cp $compiler/compile     bin/compile
+   cp $compiler/run         bin/run
+
+   cp $compiler/Makefile    .
+
+   cp $compiler/standard_tests/iso7185pat.cmp standard_tests
+   cp $compiler/standard_tests/iso7185pats.cmp standard_tests
 
    #
    # GPC has been problematic for line endings. This changes them
    # all to Unix mode for GPC compiles, which at this moment is
    # all there is. GPC for Windows has serious problems.
    #
-   unixeol
-
-   echo Compiler set to GPC Pascal
+   #unixeol
 
 else
 
@@ -80,6 +219,25 @@ else
    echo "*** compilers"
    echo
    echo "IP Pascal  - use \"ip_pascal\""
+   echo "P5C Pascal - use \"P5C\""
    echo "GPC Pascal - use \"GPC\""
 
 fi
+
+#
+# Set according to number of bits
+#
+if [ $bits = "32" ]
+then
+
+    echo "Setting for 32 bit target"
+    set32
+
+else
+
+    echo "Setting for 64 bit target"
+    set64
+
+fi
+
+echo "Configure completed!"
